local M = {}

local p = require("hugoulm.theme.palette")

function M.apply()
  local hl = vim.api.nvim_set_hl

  hl(0, "Normal",            { fg = p.fg,       bg = p.bg_dark })
  hl(0, "NormalFloat",       { fg = p.fg,       bg = p.bg_float })
  hl(0, "NormalNC",          { fg = p.fg_dark,  bg = p.bg_dark })
  hl(0, "Comment",           { fg = p.comment,  italic = true })
  hl(0, "Conceal",           { fg = p.fg_gutter })
  hl(0, "Cursor",            { fg = p.bg,       bg = p.fg })
  hl(0, "CursorIM",          { fg = p.bg,       bg = p.fg })
  hl(0, "CursorColumn",      { bg = p.bg_float })
  hl(0, "CursorLine",        { bg = p.bg_float })
  hl(0, "CursorLineNr",      { fg = p.green_dark, bold = true })
  hl(0, "LineNr",            { fg = p.fg_gutter })
  hl(0, "FoldColumn",        { fg = p.fg_gutter, bg = p.bg })
  hl(0, "Folded",            { fg = p.comment,  bg = p.bg_float })
  hl(0, "SignColumn",        { fg = p.fg_gutter, bg = p.bg })
  hl(0, "ColorColumn",       { bg = p.bg_float })

  hl(0, "Constant",          { fg = p.teal })
  hl(0, "String",            { fg = p.green })
  hl(0, "Character",         { fg = p.green_dark })
  hl(0, "Number",            { fg = p.teal })
  hl(0, "Boolean",           { fg = p.purple })
  hl(0, "Float",             { fg = p.teal })

  hl(0, "Identifier",        { fg = p.fg })
  hl(0, "Function",          { fg = p.blue })

  hl(0, "Statement",         { fg = p.purple })
  hl(0, "Conditional",       { fg = p.purple })
  hl(0, "Repeat",            { fg = p.purple })
  hl(0, "Label",             { fg = p.purple })
  hl(0, "Operator",          { fg = p.teal })
  hl(0, "Keyword",           { fg = p.purple })
  hl(0, "Exception",         { fg = p.red })

  hl(0, "PreProc",           { fg = p.blue })
  hl(0, "Include",           { fg = p.blue })
  hl(0, "Define",            { fg = p.purple })
  hl(0, "Macro",             { fg = p.purple })
  hl(0, "PreCondit",         { fg = p.purple })

  hl(0, "Type",              { fg = p.teal })
  hl(0, "StorageClass",      { fg = p.purple })
  hl(0, "Structure",         { fg = p.teal })
  hl(0, "Typedef",           { fg = p.teal })

  hl(0, "Special",           { fg = p.yellow })
  hl(0, "SpecialChar",       { fg = p.yellow })
  hl(0, "Tag",               { fg = p.green })
  hl(0, "Delimiter",         { fg = p.fg_dark })
  hl(0, "SpecialComment",    { fg = p.comment, italic = true })
  hl(0, "Debug",             { fg = p.red })

  hl(0, "Underlined",        { underline = true })
  hl(0, "Bold",              { bold = true })
  hl(0, "Italic",            { italic = true })
  hl(0, "Error",             { fg = p.red })
  hl(0, "Todo",              { fg = p.yellow, bold = true })

  hl(0, "Visual",            { bg = p.bg_visual })
  hl(0, "VisualNOS",         { bg = p.bg_visual })
  hl(0, "Search",            { fg = p.bg, bg = p.green })
  hl(0, "IncSearch",         { fg = p.bg, bg = p.purple })
  hl(0, "CurSearch",         { fg = p.bg, bg = p.green_dark })
  hl(0, "Substitute",        { fg = p.bg, bg = p.red })

  hl(0, "StatusLine",        { fg = p.fg,      bg = p.bg_dark })
  hl(0, "StatusLineNC",      { fg = p.comment, bg = p.bg_dark })
  hl(0, "WinBar",            { fg = p.fg,      bg = p.bg })
  hl(0, "WinBarNC",          { fg = p.comment, bg = p.bg })
  hl(0, "TabLine",           { fg = p.comment, bg = p.bg_dark })
  hl(0, "TabLineFill",       { bg = p.bg_dark })
  hl(0, "TabLineSel",        { fg = p.fg,      bg = p.bg, bold = true })

  hl(0, "VertSplit",         { fg = p.fg_gutter })
  hl(0, "WinSeparator",      { fg = p.fg_gutter })

  hl(0, "Pmenu",             { fg = p.fg_dark, bg = p.bg_float })
  hl(0, "PmenuSel",          { fg = p.fg,      bg = p.bg_search, bold = true })
  hl(0, "PmenuSbar",         { bg = p.bg_float })
  hl(0, "PmenuThumb",        { bg = p.fg_gutter })
  hl(0, "PmenuBorder",       { fg = p.blue,    bg = p.bg_float })

  hl(0, "NonText",           { fg = p.fg_gutter })
  hl(0, "EndOfBuffer",       { fg = p.fg_gutter })
  hl(0, "Whitespace",        { fg = p.fg_gutter })
  hl(0, "SpecialKey",        { fg = p.fg_gutter })
  hl(0, "MatchParen",        { fg = p.green, bg = p.bg_visual, bold = true })

  hl(0, "MsgArea",           { fg = p.fg_dark })
  hl(0, "MsgSeparator",      { fg = p.fg_gutter })
  hl(0, "MoreMsg",           { fg = p.green_dark, bold = true })
  hl(0, "Question",          { fg = p.green_dark })
  hl(0, "WarningMsg",        { fg = p.yellow })
  hl(0, "ErrorMsg",          { fg = p.red })

  hl(0, "DiffAdd",           { bg = p.diff_add })
  hl(0, "DiffDelete",        { bg = p.diff_del })
  hl(0, "DiffChange",        { bg = p.diff_change })
  hl(0, "DiffText",          { bg = p.diff_text })

  hl(0, "SpellBad",          { sp = p.red,    undercurl = true })
  hl(0, "SpellCap",          { sp = p.yellow, undercurl = true })
  hl(0, "SpellLocal",        { sp = p.teal,   undercurl = true })
  hl(0, "SpellRare",         { sp = p.purple, undercurl = true })

  hl(0, "Directory",         { fg = p.teal })
  hl(0, "Title",             { fg = p.purple, bold = true })
  hl(0, "QuickFixLine",      { bg = p.bg_visual })

  hl(0, "DiagnosticError",           { fg = p.red })
  hl(0, "DiagnosticWarn",            { fg = p.yellow })
  hl(0, "DiagnosticInfo",            { fg = p.teal })
  hl(0, "DiagnosticHint",            { fg = p.blue })
  hl(0, "DiagnosticOk",              { fg = p.green_dark })
  hl(0, "DiagnosticUnderlineError",  { sp = p.red,    undercurl = true })
  hl(0, "DiagnosticUnderlineWarn",   { sp = p.yellow, undercurl = true })
  hl(0, "DiagnosticUnderlineInfo",   { sp = p.teal,   undercurl = true })
  hl(0, "DiagnosticUnderlineHint",   { sp = p.blue,   undercurl = true })
  hl(0, "DiagnosticVirtualTextError",{ fg = p.red,    bg = p.diff_del })
  hl(0, "DiagnosticVirtualTextWarn", { fg = p.yellow, bg = "#2e2a18" })
  hl(0, "DiagnosticVirtualTextInfo", { fg = p.teal,   bg = "#182028" })
  hl(0, "DiagnosticVirtualTextHint", { fg = p.blue,   bg = "#18202e" })
  hl(0, "DiagnosticSignError",       { fg = p.red })
  hl(0, "DiagnosticSignWarn",        { fg = p.yellow })
  hl(0, "DiagnosticSignInfo",        { fg = p.teal })
  hl(0, "DiagnosticSignHint",        { fg = p.blue })

  hl(0, "LspReferenceText",  { bg = p.bg_visual })
  hl(0, "LspReferenceRead",  { bg = p.bg_visual })
  hl(0, "LspReferenceWrite", { bg = p.bg_visual })
  hl(0, "LspSignatureActiveParameter", { fg = p.green, bold = true })
  hl(0, "LspCodeLens",       { fg = p.comment })
  hl(0, "LspCodeLensSeparator", { fg = p.fg_gutter })

  hl(0, "@comment",                  { link = "Comment" })
  hl(0, "@comment.documentation",    { fg = p.comment, italic = true })
  hl(0, "@keyword",                  { fg = p.purple })
  hl(0, "@keyword.function",         { fg = p.purple })
  hl(0, "@keyword.operator",         { fg = p.teal })
  hl(0, "@keyword.import",           { fg = p.blue })
  hl(0, "@keyword.return",           { fg = p.purple })
  hl(0, "@keyword.exception",        { fg = p.red })
  hl(0, "@function",                 { fg = p.blue })
  hl(0, "@function.call",            { fg = p.blue })
  hl(0, "@function.macro",           { fg = p.purple })
  hl(0, "@function.method",          { fg = p.blue })
  hl(0, "@function.method.call",     { fg = p.blue })
  hl(0, "@constructor",              { fg = p.teal })
  hl(0, "@variable",                 { fg = p.fg })
  hl(0, "@variable.builtin",         { fg = p.red })
  hl(0, "@variable.parameter",       { fg = p.fg_dark, italic = true })
  hl(0, "@variable.member",          { fg = p.teal })
  hl(0, "@string",                   { fg = p.green })
  hl(0, "@string.escape",            { fg = p.yellow })
  hl(0, "@string.documentation",     { fg = p.green, italic = true })
  hl(0, "@string.regexp",            { fg = p.yellow })
  hl(0, "@constant",                 { fg = p.teal })
  hl(0, "@constant.builtin",         { fg = p.purple })
  hl(0, "@number",                   { fg = p.teal })
  hl(0, "@float",                    { fg = p.teal })
  hl(0, "@boolean",                  { fg = p.purple })
  hl(0, "@character",                { fg = p.green_dark })
  hl(0, "@type",                     { fg = p.teal })
  hl(0, "@type.definition",          { fg = p.teal })
  hl(0, "@type.builtin",             { fg = p.teal })
  hl(0, "@attribute",                { fg = p.yellow })
  hl(0, "@property",                 { fg = p.teal })
  hl(0, "@operator",                 { fg = p.teal })
  hl(0, "@punctuation.delimiter",    { fg = p.fg_dark })
  hl(0, "@punctuation.bracket",      { fg = p.fg_dark })
  hl(0, "@punctuation.special",      { fg = p.yellow })
  hl(0, "@namespace",                { fg = p.teal })
  hl(0, "@module",                   { fg = p.teal })
  hl(0, "@label",                    { fg = p.purple })
  hl(0, "@tag",                      { fg = p.red })
  hl(0, "@tag.attribute",            { fg = p.yellow })
  hl(0, "@tag.delimiter",            { fg = p.fg_dark })
  hl(0, "@markup.heading",           { fg = p.purple, bold = true })
  hl(0, "@markup.raw",               { fg = p.green })
  hl(0, "@markup.link",              { fg = p.blue, underline = true })
  hl(0, "@markup.link.label",        { fg = p.teal })
  hl(0, "@markup.italic",            { italic = true })
  hl(0, "@markup.strong",            { bold = true })
  hl(0, "@markup.strikethrough",     { strikethrough = true })
  hl(0, "@diff.plus",                { fg = p.green_dark })
  hl(0, "@diff.minus",               { fg = p.red })
  hl(0, "@diff.delta",               { fg = p.teal })

  hl(0, "GitSignsAdd",       { fg = p.green_dark })
  hl(0, "GitSignsChange",    { fg = p.teal })
  hl(0, "GitSignsDelete",    { fg = p.red })
  hl(0, "GitSignsAddNr",     { fg = p.green_dark })
  hl(0, "GitSignsChangeNr",  { fg = p.teal })
  hl(0, "GitSignsDeleteNr",  { fg = p.red })
  hl(0, "GitSignsAddLn",     { bg = p.diff_add })
  hl(0, "GitSignsChangeLn",  { bg = p.diff_change })
  hl(0, "GitSignsDeleteLn",  { bg = p.diff_del })

  hl(0, "TelescopeNormal",         { fg = p.fg_dark,  bg = p.bg_float })
  hl(0, "TelescopeBorder",         { fg = p.blue,     bg = p.bg_float })
  hl(0, "TelescopePromptNormal",   { fg = p.fg,       bg = p.bg_dark })
  hl(0, "TelescopePromptBorder",   { fg = p.purple,   bg = p.bg_dark })
  hl(0, "TelescopePromptTitle",    { fg = p.bg,       bg = p.purple, bold = true })
  hl(0, "TelescopePreviewTitle",   { fg = p.bg,       bg = p.teal,   bold = true })
  hl(0, "TelescopeResultsTitle",   { fg = p.bg,       bg = p.blue,   bold = true })
  hl(0, "TelescopeSelection",      { fg = p.fg,       bg = p.bg_search })
  hl(0, "TelescopeSelectionCaret", { fg = p.green })
  hl(0, "TelescopeMatching",       { fg = p.green,    bold = true })
  hl(0, "TelescopePromptCounter",  { fg = p.comment })

  hl(0, "NeoTreeNormal",           { fg = p.fg_dark,  bg = p.bg_dark })
  hl(0, "NeoTreeNormalNC",         { fg = p.fg_dark,  bg = p.bg_dark })
  hl(0, "NeoTreeBorder",           { fg = p.fg_gutter, bg = p.bg_dark })
  hl(0, "NeoTreeTitleBar",         { fg = p.bg,       bg = p.teal, bold = true })
  hl(0, "NeoTreeRootName",         { fg = p.teal,     bold = true })
  hl(0, "NeoTreeDirectoryName",    { fg = p.teal })
  hl(0, "NeoTreeDirectoryIcon",    { fg = p.teal })
  hl(0, "NeoTreeFileName",         { fg = p.fg_dark })
  hl(0, "NeoTreeFileIcon",         { fg = p.blue })
  hl(0, "NeoTreeGitAdded",         { fg = p.green_dark })
  hl(0, "NeoTreeGitModified",      { fg = p.yellow })
  hl(0, "NeoTreeGitDeleted",       { fg = p.red })
  hl(0, "NeoTreeGitUntracked",     { fg = p.comment })
  hl(0, "NeoTreeIndentMarker",     { fg = p.fg_gutter })
  hl(0, "NeoTreeSymbolicLinkTarget",{ fg = p.purple })

  hl(0, "CmpNormal",               { fg = p.fg_dark,  bg = p.bg_float })
  hl(0, "CmpBorder",               { fg = p.blue,     bg = p.bg_float })
  hl(0, "CmpItemAbbr",             { fg = p.fg_dark })
  hl(0, "CmpItemAbbrMatch",        { fg = p.green,    bold = true })
  hl(0, "CmpItemAbbrMatchFuzzy",   { fg = p.green_dark })
  hl(0, "CmpItemAbbrDeprecated",   { fg = p.comment,  strikethrough = true })
  hl(0, "CmpItemKind",             { fg = p.blue })
  hl(0, "CmpItemKindFunction",     { fg = p.blue })
  hl(0, "CmpItemKindMethod",       { fg = p.blue })
  hl(0, "CmpItemKindConstructor",  { fg = p.teal })
  hl(0, "CmpItemKindClass",        { fg = p.teal })
  hl(0, "CmpItemKindStruct",       { fg = p.teal })
  hl(0, "CmpItemKindInterface",    { fg = p.teal })
  hl(0, "CmpItemKindKeyword",      { fg = p.purple })
  hl(0, "CmpItemKindVariable",     { fg = p.fg })
  hl(0, "CmpItemKindField",        { fg = p.teal })
  hl(0, "CmpItemKindProperty",     { fg = p.teal })
  hl(0, "CmpItemKindConstant",     { fg = p.teal })
  hl(0, "CmpItemKindEnum",         { fg = p.teal })
  hl(0, "CmpItemKindEnumMember",   { fg = p.teal })
  hl(0, "CmpItemKindValue",        { fg = p.teal })
  hl(0, "CmpItemKindText",         { fg = p.fg_dark })
  hl(0, "CmpItemKindSnippet",      { fg = p.yellow })
  hl(0, "CmpItemKindModule",       { fg = p.teal })
  hl(0, "CmpItemKindUnit",         { fg = p.teal })
  hl(0, "CmpItemMenu",             { fg = p.comment })

  hl(0, "WhichKey",          { fg = p.green })
  hl(0, "WhichKeyGroup",     { fg = p.blue })
  hl(0, "WhichKeyDesc",      { fg = p.fg_dark })
  hl(0, "WhichKeySeparator", { fg = p.fg_gutter })
  hl(0, "WhichKeyValue",     { fg = p.comment })
  hl(0, "WhichKeyBorder",    { fg = p.purple })
  hl(0, "WhichKeyNormal",    { bg = p.bg_float })

  hl(0, "DapBreakpoint",     { fg = p.red })
  hl(0, "DapBreakpointCondition", { fg = p.yellow })
  hl(0, "DapLogPoint",       { fg = p.blue })
  hl(0, "DapStopped",        { fg = p.green_dark })
  hl(0, "DapStoppedLine",    { bg = p.diff_add })

  hl(0, "SnacksNormal",      { fg = p.fg,      bg = p.bg_float })
  hl(0, "SnacksBorder",      { fg = p.purple,  bg = p.bg_float })
  hl(0, "SnacksTitle",       { fg = p.bg,      bg = p.purple, bold = true })
  hl(0, "SnacksInputBorder", { fg = p.green,   bg = p.bg_float })
  hl(0, "SnacksInputNormal", { fg = p.fg,      bg = p.bg_float })
  hl(0, "SnacksDashboardHeader",  { fg = p.purple })
  hl(0, "SnacksDashboardFooter",  { fg = p.comment })
  hl(0, "SnacksDashboardKey",     { fg = p.green })
  hl(0, "SnacksDashboardDesc",    { fg = p.fg_dark })
  hl(0, "SnacksDashboardIcon",    { fg = p.teal })

  hl(0, "HarpoonBorder",     { fg = p.teal })
  hl(0, "HarpoonWindow",     { fg = p.fg,  bg = p.bg_float })

  hl(0, "IlluminatedWordText",  { bg = p.bg_visual })
  hl(0, "IlluminatedWordRead",  { bg = p.bg_visual })
  hl(0, "IlluminatedWordWrite", { bg = p.bg_visual })
end

return M
